namespace: drew1kun
name: shellfreak
version: 1.1.23
readme: README.md
authors:
- Andrew Shagayev <drew-kun@protonmail.com>
description: Ansible Collection for slick and freakish shell experience.

# The path to the license file for the collection. This path is relative to the root of the collection. This key is
# mutually exclusive with 'license'
license_file: 'LICENSE'
tags:
- shell
- ohmyzsh
- oh_my_zsh
- mpd
- mpc
- ncmpcpp
- nvim
- neovim
- tmux
- macos
- mac
- linux

#dependencies:
#  community.general: ">=3.0.0"

repository: https://github.com/drew1kun/ansible-collection-shellfreak.git
documentation: https://github.com/drew1kun/ansible-collection-shellfreak/blob/main/README.md
homepage: https://github.com/drew1kun/ansible-collection-shellfreak
issues: https://github.com/drew1kun/ansible-collection-shellfreak/issues

build_ignore:
- '*.tar.gz'
- 'signatures'
- 'galaxy-publish.yml'
