---
galaxy_info:
  role_name: mpd
  author: drew1kun
  description: |
    Role that installs and configures mpd, mpc and ncmpcpp.
  license: MIT
  min_ansible_version: "1.2"
  github_branch: main
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - media
    - player
    - daemon
    - mpd
    - mpc
    - ncmpcpp
    - shell
    - shellfreak
    - cmdline
    - terminal
    - ubuntu
    - trusty
    - kali
    - debian
    - wheezy
    - jessie
    - stretch
    - buster
    - bullseye
    - macos
    - osx
