---
- name: '[darwin] Install mpd with Homebrew'
  community.general.homebrew:
    name:
      - mpd
      - mpc
      - ncmpcpp
    state: present

# - name: '[darwin] Check if ~/Library/LaunchAgents/homebrew.mxcl.mpd.plist exists'
#   ansible.builtin.stat:
#     path: ~/Library/LaunchAgents/homebrew.mxcl.mpd.plist
#   register: mpd_stat_plist
#
# - name: '[darwin] Enable mpd service to start on login'
#   ansible.builtin.command: brew services start mpd
#   environment:
#     PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"
#   changed_when: true
#   when:
#     - mpd_autostart
#     - not mpd_stat_plist.stat.exists

- name: '[darwin] Manage mpd service'
  community.general.homebrew_services:
    name: mpd
    state: "{{ 'present' if mpd_autostart else 'absent' }}"
  when: mpd_autostart

- name: '[darwin] Create ~/.mpd/ directory for each mpd_user'   # noqa: key-order[task]
  ansible.builtin.file:
    path: "{{ mpd_user_home }}/.mpd"
    state: directory
    mode: "0755"
    <<: &mpd_file_ownership
      owner: "{{ mpd_user }}"  # Works only if gathering facts. Turns to root if using 'become: true'
      group: staff
  <<: &mpd_users_loop_become_when
    become: true
    loop: "{{ mpd_users }}"
    loop_control:
      loop_var: mpd_user
      label: "{{ mpd_user }}"
    when:
      - mpd_users is defined
      - mpd_users | length > 0
      - mpd_user != 'root'
    vars:
      mpd_user_home: "{{ '/Users/' ~ mpd_user }}"

- name: '[darwin] Generate mpd.conf from template for each mpd_user'  # noqa: key-order[task]
  ansible.builtin.template:
    src: mpd.conf.j2
    dest: "{{ mpd_user_home }}/.mpd/mpd.conf"
    backup: true
    mode: "0644"
    <<: *mpd_file_ownership
  <<: *mpd_users_loop_become_when
  notify: Restart mpd service with brew services command

- name: "Ncmpcpp block"
  tags: ['ncmpcpp']
  block:
    - name: '[darwin] Create ~/.ncmpcpp folder for each mpd_user'   # noqa: key-order[task]
      ansible.builtin.file:
        path: "{{ mpd_user_home }}/.ncmpcpp"
        state: directory
        mode: "0755"
        <<: *mpd_file_ownership
      <<: *mpd_users_loop_become_when

    - name: '[darwin] Generate ncmpcpp config from template for each mpd_user'  # noqa: key-order[task]
      ansible.builtin.template:
        src: ncmpcpp.conf.j2
        dest: "{{ mpd_user_home }}/.ncmpcpp/config"
        mode: "0644"
        <<: *mpd_file_ownership
      <<: *mpd_users_loop_become_when
