---
- name: '[linux] Update apt cache on Debian-like systems'
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: ansible_os_family == 'Debian'

- name: '[linux] Install mpd package'
  ansible.builtin.package:
    name:
      - mpd
      - mpc
      - ncmpcpp
    state: present
  become: true
  tags:
    - mpd_mpc
    - mpd_ncmpcpp

- name: '[linux] Enable and Start mpd service if needed'
  ansible.builtin.service:
    name: "{{ mpd_service.name }}"
    enabled: "{{ mpd_service.enabled }}"
    state: "{{ mpd_service.state }}"
  become: true
  loop:
    - name: mpd
      enabled: "{{ mpd_autostart }}"
      state: "{{ 'started' if mpd_autostart else 'stopped' }}"
    - name: mpd.socket
      enabled: "{{ not mpd_autostart }}"
      state: "{{ 'stopped' if mpd_autostart else 'started' }}"
  loop_control:
    loop_var: mpd_service
    label: "{{ mpd_service.name }}: enabled: {{ mpd_service.enabled }}, {{ mpd_service.state }}"

- name: '[linux] Generate mpd.conf from template'
  ansible.builtin.template:
    src: mpd.conf.j2
    dest: /etc/mpd.conf
    backup: true
    owner: root
    group: root
    mode: "0644"
  notify: Restart mpd service
  become: true

- name: 'Ncmpcpp config block'
  become: true
  when:
    - mpd_users is defined
    - mpd_users | length > 0
  tags: ['mpd_ncmpcpp']
  block:
    - name: '[linux] Create ~/.ncmpcpp folder for each mpd_user'  # noqa: key-order[task]
      ansible.builtin.file:
        path: "{{ '' if mpd_user == 'root' else '/home' }}/{{ mpd_user }}/.ncmpcpp"
        state: directory
        <<: &mpd_ownership
          owner: "{{ mpd_user }}"
          group: "{{ mpd_user }}"
        mode: "0755"
      <<: &mpd_users_loop
        loop: "{{ mpd_users }}"
        loop_control:
          loop_var: mpd_user
          label: "{{ mpd_user }}"

    - name: '[linux] Generate ncmpcpp config from template for each mpd_user'   # noqa: key-order[task]
      ansible.builtin.template:
        <<: *mpd_ownership
        src: ncmpcpp.conf.j2
        dest: "{{ '' if mpd_user == 'root' else '/home' }}/{{ mpd_user }}/.ncmpcpp/config"
        mode: "0644"
      <<: *mpd_users_loop

- name: '[linux] Check firewalld stats'
  ansible.builtin.stat:
    path: "{{ item }}"
  register: mpd_stat_firewalld
  become: true
  loop:
    - /usr/sbin/firewalld
    - /sbin/firewalld
  when: mpd_firewalld|default(false)|bool

- name: '[linux] Open mpd port in firewall'
  ansible.posix.firewalld:
    port: "{{ mpd_port }}/tcp"
    zone: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ mpd_firewalld_zones }}"
  become: true
  when:
    - mpd_firewalld|default(false)|bool
    - mpd_stat_firewalld.results[0].stat.exists
      or
      mpd_stat_firewalld.results[1].stat.exists
  vars:
    ansible_python_interpreter: '/usr/bin/python3'  # Fix the "Python Module not found.." Error
