---
# Both Plug and Vundle need git for plugins installation
- name: "[dependencies] Non-MacOS: Install git, ag, ripgrep and CTags"
  ansible.builtin.package:
    name:
      - fzf
      - git
      - ripgrep
      - silversearcher-ag
      - exuberant-ctags
      - neovim
    state: present
  become: true
  register: vim_deps_result
  when: ansible_system != 'Darwin'

- name: "[dependencies] MacOS: Install git, ag, ripgrep"
  community.general.homebrew:
    state: present
    name:
      - ag
      - fzf
      - git
      - ripgrep
      - neovim
  become: false
  register: vim_deps_result
  when: ansible_system == 'Darwin'
