# This tmux statusbar config was created by tmuxline.vim
# on Wed, 31 Dec 2025

set -g status-justify "centre"
set -g status "on"
set -g status-left-style "none"
set -g message-command-style "fg=colour250,bg=colour238"
set -g status-right-style "none"
set -g pane-active-border-style "fg=colour106"
set -g status-style "none,bg=colour235"
set -g message-style "fg=colour250,bg=colour238"
set -g pane-border-style "fg=colour238"
set -g status-right-length "100"
set -g status-left-length "100"
setw -g window-status-activity-style "underscore,fg=colour106,bg=colour235"
setw -g window-status-separator ""
setw -g window-status-style "none,fg=colour106,bg=colour235"
set -g status-left "#[fg=colour235,bg=colour106] #S #[fg=colour106,bg=colour238,nobold,nounderscore,noitalics]#[fg=colour250,bg=colour238] #F #[fg=colour238,bg=colour235,nobold,nounderscore,noitalics]#[fg=colour106,bg=colour235] #W #[fg=colour235,bg=colour235,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=colour235,bg=colour235,nobold,nounderscore,noitalics]#[fg=colour106,bg=colour235] %a #[fg=colour238,bg=colour235,nobold,nounderscore,noitalics]#[fg=colour250,bg=colour238] %b %d  %R #[fg=colour106,bg=colour238,nobold,nounderscore,noitalics]#[fg=colour235,bg=colour106] #H "
setw -g window-status-format "#[fg=colour235,bg=colour235,nobold,nounderscore,noitalics]#[default] #I  #W #[fg=colour235,bg=colour235,nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=colour235,bg=colour238,nobold,nounderscore,noitalics]#[fg=colour250,bg=colour238] #I  #W #[fg=colour238,bg=colour235,nobold,nounderscore,noitalics]"
